on:
  release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os:
          - name: win
            filename: indra.exe
          - name: mac
            filename: indra
          - name: linux
            filename: indra
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version-file: .tool-versions

      - name: build binary
        run: deno run ${{ matrix.os.name }}

      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os.name }}
          path: ${{ matrix.os.filename }}
