name: Upload binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os:
          - name: win
            filename: indra.exe
          - name: mac
            filename: indra
          - name: linux
            filename: indra
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version-file: .tool-versions

      - name: build binary
        run: deno run ${{ matrix.os.name }}

      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: indra-${{ matrix.os.name }}.zip
          path: ${{ matrix.os.filename }}

      - uses: softprops/action-gh-release@v2
        with:
          files: indra-${{ matrix.os.name }}.zip
